name: CI run tests

on: [push]

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    - uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: '2.7'
    - name: Install dependancies
      run: bundle install
    - name: Run tests
      run: rspec   